/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class xflaim_OptType */

#ifndef _Included_xflaim_OptType
#define _Included_xflaim_OptType
#ifdef __cplusplus
extern "C" {
#endif
#undef xflaim_OptType_XFLM_QOPT_NONE
#define xflaim_OptType_XFLM_QOPT_NONE 0L
#undef xflaim_OptType_XFLM_QOPT_USING_INDEX
#define xflaim_OptType_XFLM_QOPT_USING_INDEX 1L
#undef xflaim_OptType_XFLM_QOPT_FULL_COLLECTION_SCAN
#define xflaim_OptType_XFLM_QOPT_FULL_COLLECTION_SCAN 2L
#undef xflaim_OptType_XFLM_QOPT_SINGLE_NODE_ID
#define xflaim_OptType_XFLM_QOPT_SINGLE_NODE_ID 3L
#undef xflaim_OptType_XFLM_QOPT_NODE_ID_RANGE
#define xflaim_OptType_XFLM_QOPT_NODE_ID_RANGE 4L
#ifdef __cplusplus
}
#endif
#endif
