/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class xflaim_FlmDictIndex */

#ifndef _Included_xflaim_FlmDictIndex
#define _Included_xflaim_FlmDictIndex
#ifdef __cplusplus
extern "C" {
#endif
#undef xflaim_FlmDictIndex_MAX_INDEX_NUM
#define xflaim_FlmDictIndex_MAX_INDEX_NUM 65500L
#undef xflaim_FlmDictIndex_NUMBER_INDEX
#define xflaim_FlmDictIndex_NUMBER_INDEX 65534L
#undef xflaim_FlmDictIndex_NAME_INDEX
#define xflaim_FlmDictIndex_NAME_INDEX 65535L
#ifdef __cplusplus
}
#endif
#endif
