/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class xflaim_DiskIOStat */

#ifndef _Included_xflaim_DiskIOStat
#define _Included_xflaim_DiskIOStat
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     xflaim_DiskIOStat
 * Method:    initIDs
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_xflaim_DiskIOStat_initIDs
  (JNIEnv *, jclass);

#ifdef __cplusplus
}
#endif
#endif
