/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class xflaim_DefaultRestoreClient */

#ifndef _Included_xflaim_DefaultRestoreClient
#define _Included_xflaim_DefaultRestoreClient
#ifdef __cplusplus
extern "C" {
#endif
#ifdef __cplusplus
}
#endif
#endif
