/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class xflaim_ExportFormatType */

#ifndef _Included_xflaim_ExportFormatType
#define _Included_xflaim_ExportFormatType
#ifdef __cplusplus
extern "C" {
#endif
#undef xflaim_ExportFormatType_XFLM_EXPORT_NO_FORMAT
#define xflaim_ExportFormatType_XFLM_EXPORT_NO_FORMAT 0L
#undef xflaim_ExportFormatType_XFLM_EXPORT_NEW_LINE
#define xflaim_ExportFormatType_XFLM_EXPORT_NEW_LINE 1L
#undef xflaim_ExportFormatType_XFLM_EXPORT_INDENT
#define xflaim_ExportFormatType_XFLM_EXPORT_INDENT 2L
#undef xflaim_ExportFormatType_XFLM_EXPORT_INDENT_DATA
#define xflaim_ExportFormatType_XFLM_EXPORT_INDENT_DATA 3L
#ifdef __cplusplus
}
#endif
#endif
