/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class xflaim_XFlaimException */

#ifndef _Included_xflaim_XFlaimException
#define _Included_xflaim_XFlaimException
#ifdef __cplusplus
extern "C" {
#endif
#undef xflaim_XFlaimException_serialVersionUID
#define xflaim_XFlaimException_serialVersionUID -3042686055658047285LL
#undef xflaim_XFlaimException_serialVersionUID
#define xflaim_XFlaimException_serialVersionUID -3387516993124229948LL
#ifdef __cplusplus
}
#endif
#endif
