/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class xflaim_Db */

#ifndef _Included_xflaim_Db
#define _Included_xflaim_Db
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     xflaim_Db
 * Method:    _release
 * Signature: (J)V
 */
JNIEXPORT void JNICALL Java_xflaim_Db__1release
  (JNIEnv *, jobject, jlong);

/*
 * Class:     xflaim_Db
 * Method:    _transBegin
 * Signature: (JIII)V
 */
JNIEXPORT void JNICALL Java_xflaim_Db__1transBegin__JIII
  (JNIEnv *, jobject, jlong, jint, jint, jint);

/*
 * Class:     xflaim_Db
 * Method:    _transBegin
 * Signature: (JJ)V
 */
JNIEXPORT void JNICALL Java_xflaim_Db__1transBegin__JJ
  (JNIEnv *, jobject, jlong, jlong);

/*
 * Class:     xflaim_Db
 * Method:    _transCommit
 * Signature: (J)V
 */
JNIEXPORT void JNICALL Java_xflaim_Db__1transCommit
  (JNIEnv *, jobject, jlong);

/*
 * Class:     xflaim_Db
 * Method:    _transAbort
 * Signature: (J)V
 */
JNIEXPORT void JNICALL Java_xflaim_Db__1transAbort
  (JNIEnv *, jobject, jlong);

/*
 * Class:     xflaim_Db
 * Method:    _getTransType
 * Signature: (J)I
 */
JNIEXPORT jint JNICALL Java_xflaim_Db__1getTransType
  (JNIEnv *, jobject, jlong);

/*
 * Class:     xflaim_Db
 * Method:    _doCheckpoint
 * Signature: (JI)V
 */
JNIEXPORT void JNICALL Java_xflaim_Db__1doCheckpoint
  (JNIEnv *, jobject, jlong, jint);

/*
 * Class:     xflaim_Db
 * Method:    _dbLock
 * Signature: (JIII)V
 */
JNIEXPORT void JNICALL Java_xflaim_Db__1dbLock
  (JNIEnv *, jobject, jlong, jint, jint, jint);

/*
 * Class:     xflaim_Db
 * Method:    _dbUnlock
 * Signature: (J)V
 */
JNIEXPORT void JNICALL Java_xflaim_Db__1dbUnlock
  (JNIEnv *, jobject, jlong);

/*
 * Class:     xflaim_Db
 * Method:    _getLockType
 * Signature: (J)I
 */
JNIEXPORT jint JNICALL Java_xflaim_Db__1getLockType
  (JNIEnv *, jobject, jlong);

/*
 * Class:     xflaim_Db
 * Method:    _getLockImplicit
 * Signature: (J)Z
 */
JNIEXPORT jboolean JNICALL Java_xflaim_Db__1getLockImplicit
  (JNIEnv *, jobject, jlong);

/*
 * Class:     xflaim_Db
 * Method:    _getLockThreadId
 * Signature: (J)I
 */
JNIEXPORT jint JNICALL Java_xflaim_Db__1getLockThreadId
  (JNIEnv *, jobject, jlong);

/*
 * Class:     xflaim_Db
 * Method:    _getLockNumExclQueued
 * Signature: (J)I
 */
JNIEXPORT jint JNICALL Java_xflaim_Db__1getLockNumExclQueued
  (JNIEnv *, jobject, jlong);

/*
 * Class:     xflaim_Db
 * Method:    _getLockNumSharedQueued
 * Signature: (J)I
 */
JNIEXPORT jint JNICALL Java_xflaim_Db__1getLockNumSharedQueued
  (JNIEnv *, jobject, jlong);

/*
 * Class:     xflaim_Db
 * Method:    _getLockPriorityCount
 * Signature: (JI)I
 */
JNIEXPORT jint JNICALL Java_xflaim_Db__1getLockPriorityCount
  (JNIEnv *, jobject, jlong, jint);

/*
 * Class:     xflaim_Db
 * Method:    _indexSuspend
 * Signature: (JI)V
 */
JNIEXPORT void JNICALL Java_xflaim_Db__1indexSuspend
  (JNIEnv *, jobject, jlong, jint);

/*
 * Class:     xflaim_Db
 * Method:    _indexResume
 * Signature: (JI)V
 */
JNIEXPORT void JNICALL Java_xflaim_Db__1indexResume
  (JNIEnv *, jobject, jlong, jint);

/*
 * Class:     xflaim_Db
 * Method:    _indexGetNext
 * Signature: (JI)I
 */
JNIEXPORT jint JNICALL Java_xflaim_Db__1indexGetNext
  (JNIEnv *, jobject, jlong, jint);

/*
 * Class:     xflaim_Db
 * Method:    _indexStatus
 * Signature: (JI)Lxflaim/IndexStatus;
 */
JNIEXPORT jobject JNICALL Java_xflaim_Db__1indexStatus
  (JNIEnv *, jobject, jlong, jint);

/*
 * Class:     xflaim_Db
 * Method:    _reduceSize
 * Signature: (JI)I
 */
JNIEXPORT jint JNICALL Java_xflaim_Db__1reduceSize
  (JNIEnv *, jobject, jlong, jint);

/*
 * Class:     xflaim_Db
 * Method:    _keyRetrieve
 * Signature: (JIJIJ)V
 */
JNIEXPORT void JNICALL Java_xflaim_Db__1keyRetrieve
  (JNIEnv *, jobject, jlong, jint, jlong, jint, jlong);

/*
 * Class:     xflaim_Db
 * Method:    _createDocument
 * Signature: (JI)J
 */
JNIEXPORT jlong JNICALL Java_xflaim_Db__1createDocument
  (JNIEnv *, jobject, jlong, jint);

/*
 * Class:     xflaim_Db
 * Method:    _createRootElement
 * Signature: (JII)J
 */
JNIEXPORT jlong JNICALL Java_xflaim_Db__1createRootElement
  (JNIEnv *, jobject, jlong, jint, jint);

/*
 * Class:     xflaim_Db
 * Method:    _getFirstDocument
 * Signature: (JIJ)J
 */
JNIEXPORT jlong JNICALL Java_xflaim_Db__1getFirstDocument
  (JNIEnv *, jobject, jlong, jint, jlong);

/*
 * Class:     xflaim_Db
 * Method:    _getLastDocument
 * Signature: (JIJ)J
 */
JNIEXPORT jlong JNICALL Java_xflaim_Db__1getLastDocument
  (JNIEnv *, jobject, jlong, jint, jlong);

/*
 * Class:     xflaim_Db
 * Method:    _getDocument
 * Signature: (JIIJJ)J
 */
JNIEXPORT jlong JNICALL Java_xflaim_Db__1getDocument
  (JNIEnv *, jobject, jlong, jint, jint, jlong, jlong);

/*
 * Class:     xflaim_Db
 * Method:    _documentDone
 * Signature: (JIJ)V
 */
JNIEXPORT void JNICALL Java_xflaim_Db__1documentDone__JIJ
  (JNIEnv *, jobject, jlong, jint, jlong);

/*
 * Class:     xflaim_Db
 * Method:    _documentDone
 * Signature: (JJ)V
 */
JNIEXPORT void JNICALL Java_xflaim_Db__1documentDone__JJ
  (JNIEnv *, jobject, jlong, jlong);

/*
 * Class:     xflaim_Db
 * Method:    _createElementDef
 * Signature: (JLjava/lang/String;Ljava/lang/String;II)I
 */
JNIEXPORT jint JNICALL Java_xflaim_Db__1createElementDef
  (JNIEnv *, jobject, jlong, jstring, jstring, jint, jint);

/*
 * Class:     xflaim_Db
 * Method:    _createUniqueElmDef
 * Signature: (JLjava/lang/String;Ljava/lang/String;I)I
 */
JNIEXPORT jint JNICALL Java_xflaim_Db__1createUniqueElmDef
  (JNIEnv *, jobject, jlong, jstring, jstring, jint);

/*
 * Class:     xflaim_Db
 * Method:    _getElementNameId
 * Signature: (JLjava/lang/String;Ljava/lang/String;)I
 */
JNIEXPORT jint JNICALL Java_xflaim_Db__1getElementNameId
  (JNIEnv *, jobject, jlong, jstring, jstring);

/*
 * Class:     xflaim_Db
 * Method:    _createAttributeDef
 * Signature: (JLjava/lang/String;Ljava/lang/String;II)I
 */
JNIEXPORT jint JNICALL Java_xflaim_Db__1createAttributeDef
  (JNIEnv *, jobject, jlong, jstring, jstring, jint, jint);

/*
 * Class:     xflaim_Db
 * Method:    _getAttributeNameId
 * Signature: (JLjava/lang/String;Ljava/lang/String;)I
 */
JNIEXPORT jint JNICALL Java_xflaim_Db__1getAttributeNameId
  (JNIEnv *, jobject, jlong, jstring, jstring);

/*
 * Class:     xflaim_Db
 * Method:    _createPrefixDef
 * Signature: (JLjava/lang/String;I)I
 */
JNIEXPORT jint JNICALL Java_xflaim_Db__1createPrefixDef
  (JNIEnv *, jobject, jlong, jstring, jint);

/*
 * Class:     xflaim_Db
 * Method:    _getPrefixId
 * Signature: (JLjava/lang/String;)I
 */
JNIEXPORT jint JNICALL Java_xflaim_Db__1getPrefixId
  (JNIEnv *, jobject, jlong, jstring);

/*
 * Class:     xflaim_Db
 * Method:    _createEncDef
 * Signature: (JLjava/lang/String;Ljava/lang/String;II)I
 */
JNIEXPORT jint JNICALL Java_xflaim_Db__1createEncDef
  (JNIEnv *, jobject, jlong, jstring, jstring, jint, jint);

/*
 * Class:     xflaim_Db
 * Method:    _getEncDefId
 * Signature: (JLjava/lang/String;)I
 */
JNIEXPORT jint JNICALL Java_xflaim_Db__1getEncDefId
  (JNIEnv *, jobject, jlong, jstring);

/*
 * Class:     xflaim_Db
 * Method:    _createCollectionDef
 * Signature: (JLjava/lang/String;II)I
 */
JNIEXPORT jint JNICALL Java_xflaim_Db__1createCollectionDef
  (JNIEnv *, jobject, jlong, jstring, jint, jint);

/*
 * Class:     xflaim_Db
 * Method:    _getCollectionNumber
 * Signature: (JLjava/lang/String;)I
 */
JNIEXPORT jint JNICALL Java_xflaim_Db__1getCollectionNumber
  (JNIEnv *, jobject, jlong, jstring);

/*
 * Class:     xflaim_Db
 * Method:    _getIndexNumber
 * Signature: (JLjava/lang/String;)I
 */
JNIEXPORT jint JNICALL Java_xflaim_Db__1getIndexNumber
  (JNIEnv *, jobject, jlong, jstring);

/*
 * Class:     xflaim_Db
 * Method:    _getDictionaryDef
 * Signature: (JIIJ)J
 */
JNIEXPORT jlong JNICALL Java_xflaim_Db__1getDictionaryDef
  (JNIEnv *, jobject, jlong, jint, jint, jlong);

/*
 * Class:     xflaim_Db
 * Method:    _getDictionaryName
 * Signature: (JII)Ljava/lang/String;
 */
JNIEXPORT jstring JNICALL Java_xflaim_Db__1getDictionaryName
  (JNIEnv *, jobject, jlong, jint, jint);

/*
 * Class:     xflaim_Db
 * Method:    _getElementNamespace
 * Signature: (JI)Ljava/lang/String;
 */
JNIEXPORT jstring JNICALL Java_xflaim_Db__1getElementNamespace
  (JNIEnv *, jobject, jlong, jint);

/*
 * Class:     xflaim_Db
 * Method:    _getAttributeNamespace
 * Signature: (JI)Ljava/lang/String;
 */
JNIEXPORT jstring JNICALL Java_xflaim_Db__1getAttributeNamespace
  (JNIEnv *, jobject, jlong, jint);

/*
 * Class:     xflaim_Db
 * Method:    _getNode
 * Signature: (JIJJ)J
 */
JNIEXPORT jlong JNICALL Java_xflaim_Db__1getNode
  (JNIEnv *, jobject, jlong, jint, jlong, jlong);

/*
 * Class:     xflaim_Db
 * Method:    _getAttribute
 * Signature: (JIJIJ)J
 */
JNIEXPORT jlong JNICALL Java_xflaim_Db__1getAttribute
  (JNIEnv *, jobject, jlong, jint, jlong, jint, jlong);

/*
 * Class:     xflaim_Db
 * Method:    _getDataType
 * Signature: (JII)I
 */
JNIEXPORT jint JNICALL Java_xflaim_Db__1getDataType
  (JNIEnv *, jobject, jlong, jint, jint);

/*
 * Class:     xflaim_Db
 * Method:    _backupBegin
 * Signature: (JIIIJ)J
 */
JNIEXPORT jlong JNICALL Java_xflaim_Db__1backupBegin
  (JNIEnv *, jobject, jlong, jint, jint, jint, jlong);

/*
 * Class:     xflaim_Db
 * Method:    _import
 * Signature: (JJIJI)Lxflaim/ImportStats;
 */
JNIEXPORT jobject JNICALL Java_xflaim_Db__1import
  (JNIEnv *, jobject, jlong, jlong, jint, jlong, jint);

/*
 * Class:     xflaim_Db
 * Method:    _changeItemState
 * Signature: (JIILjava/lang/String;)V
 */
JNIEXPORT void JNICALL Java_xflaim_Db__1changeItemState
  (JNIEnv *, jobject, jlong, jint, jint, jstring);

/*
 * Class:     xflaim_Db
 * Method:    _getRflFileName
 * Signature: (JIZ)Ljava/lang/String;
 */
JNIEXPORT jstring JNICALL Java_xflaim_Db__1getRflFileName
  (JNIEnv *, jobject, jlong, jint, jboolean);

/*
 * Class:     xflaim_Db
 * Method:    _setNextNodeId
 * Signature: (JIJ)V
 */
JNIEXPORT void JNICALL Java_xflaim_Db__1setNextNodeId
  (JNIEnv *, jobject, jlong, jint, jlong);

/*
 * Class:     xflaim_Db
 * Method:    _setNextDictNum
 * Signature: (JII)V
 */
JNIEXPORT void JNICALL Java_xflaim_Db__1setNextDictNum
  (JNIEnv *, jobject, jlong, jint, jint);

/*
 * Class:     xflaim_Db
 * Method:    _setRflKeepFilesFlag
 * Signature: (JZ)V
 */
JNIEXPORT void JNICALL Java_xflaim_Db__1setRflKeepFilesFlag
  (JNIEnv *, jobject, jlong, jboolean);

/*
 * Class:     xflaim_Db
 * Method:    _getRflKeepFlag
 * Signature: (J)Z
 */
JNIEXPORT jboolean JNICALL Java_xflaim_Db__1getRflKeepFlag
  (JNIEnv *, jobject, jlong);

/*
 * Class:     xflaim_Db
 * Method:    _setRflDir
 * Signature: (JLjava/lang/String;)V
 */
JNIEXPORT void JNICALL Java_xflaim_Db__1setRflDir
  (JNIEnv *, jobject, jlong, jstring);

/*
 * Class:     xflaim_Db
 * Method:    _getRflDir
 * Signature: (J)Ljava/lang/String;
 */
JNIEXPORT jstring JNICALL Java_xflaim_Db__1getRflDir
  (JNIEnv *, jobject, jlong);

/*
 * Class:     xflaim_Db
 * Method:    _getRflFileNum
 * Signature: (J)I
 */
JNIEXPORT jint JNICALL Java_xflaim_Db__1getRflFileNum
  (JNIEnv *, jobject, jlong);

/*
 * Class:     xflaim_Db
 * Method:    _getHighestNotUsedRflFileNum
 * Signature: (J)I
 */
JNIEXPORT jint JNICALL Java_xflaim_Db__1getHighestNotUsedRflFileNum
  (JNIEnv *, jobject, jlong);

/*
 * Class:     xflaim_Db
 * Method:    _setRflFileSizeLimits
 * Signature: (JII)V
 */
JNIEXPORT void JNICALL Java_xflaim_Db__1setRflFileSizeLimits
  (JNIEnv *, jobject, jlong, jint, jint);

/*
 * Class:     xflaim_Db
 * Method:    _getMinRflFileSize
 * Signature: (J)I
 */
JNIEXPORT jint JNICALL Java_xflaim_Db__1getMinRflFileSize
  (JNIEnv *, jobject, jlong);

/*
 * Class:     xflaim_Db
 * Method:    _getMaxRflFileSize
 * Signature: (J)I
 */
JNIEXPORT jint JNICALL Java_xflaim_Db__1getMaxRflFileSize
  (JNIEnv *, jobject, jlong);

/*
 * Class:     xflaim_Db
 * Method:    _rflRollToNextFile
 * Signature: (J)V
 */
JNIEXPORT void JNICALL Java_xflaim_Db__1rflRollToNextFile
  (JNIEnv *, jobject, jlong);

/*
 * Class:     xflaim_Db
 * Method:    _setKeepAbortedTransInRflFlag
 * Signature: (JZ)V
 */
JNIEXPORT void JNICALL Java_xflaim_Db__1setKeepAbortedTransInRflFlag
  (JNIEnv *, jobject, jlong, jboolean);

/*
 * Class:     xflaim_Db
 * Method:    _getKeepAbortedTransInRflFlag
 * Signature: (J)Z
 */
JNIEXPORT jboolean JNICALL Java_xflaim_Db__1getKeepAbortedTransInRflFlag
  (JNIEnv *, jobject, jlong);

/*
 * Class:     xflaim_Db
 * Method:    _setAutoTurnOffKeepRflFlag
 * Signature: (JZ)V
 */
JNIEXPORT void JNICALL Java_xflaim_Db__1setAutoTurnOffKeepRflFlag
  (JNIEnv *, jobject, jlong, jboolean);

/*
 * Class:     xflaim_Db
 * Method:    _getAutoTurnOffKeepRflFlag
 * Signature: (J)Z
 */
JNIEXPORT jboolean JNICALL Java_xflaim_Db__1getAutoTurnOffKeepRflFlag
  (JNIEnv *, jobject, jlong);

/*
 * Class:     xflaim_Db
 * Method:    _setFileExtendSize
 * Signature: (JI)V
 */
JNIEXPORT void JNICALL Java_xflaim_Db__1setFileExtendSize
  (JNIEnv *, jobject, jlong, jint);

/*
 * Class:     xflaim_Db
 * Method:    _getFileExtendSize
 * Signature: (J)I
 */
JNIEXPORT jint JNICALL Java_xflaim_Db__1getFileExtendSize
  (JNIEnv *, jobject, jlong);

/*
 * Class:     xflaim_Db
 * Method:    _getDbVersion
 * Signature: (J)I
 */
JNIEXPORT jint JNICALL Java_xflaim_Db__1getDbVersion
  (JNIEnv *, jobject, jlong);

/*
 * Class:     xflaim_Db
 * Method:    _getBlockSize
 * Signature: (J)I
 */
JNIEXPORT jint JNICALL Java_xflaim_Db__1getBlockSize
  (JNIEnv *, jobject, jlong);

/*
 * Class:     xflaim_Db
 * Method:    _getDefaultLanguage
 * Signature: (J)I
 */
JNIEXPORT jint JNICALL Java_xflaim_Db__1getDefaultLanguage
  (JNIEnv *, jobject, jlong);

/*
 * Class:     xflaim_Db
 * Method:    _getTransID
 * Signature: (J)J
 */
JNIEXPORT jlong JNICALL Java_xflaim_Db__1getTransID
  (JNIEnv *, jobject, jlong);

/*
 * Class:     xflaim_Db
 * Method:    _getDbControlFileName
 * Signature: (J)Ljava/lang/String;
 */
JNIEXPORT jstring JNICALL Java_xflaim_Db__1getDbControlFileName
  (JNIEnv *, jobject, jlong);

/*
 * Class:     xflaim_Db
 * Method:    _getLastBackupTransID
 * Signature: (J)J
 */
JNIEXPORT jlong JNICALL Java_xflaim_Db__1getLastBackupTransID
  (JNIEnv *, jobject, jlong);

/*
 * Class:     xflaim_Db
 * Method:    _getBlocksChangedSinceBackup
 * Signature: (J)I
 */
JNIEXPORT jint JNICALL Java_xflaim_Db__1getBlocksChangedSinceBackup
  (JNIEnv *, jobject, jlong);

/*
 * Class:     xflaim_Db
 * Method:    _getNextIncBackupSequenceNum
 * Signature: (J)I
 */
JNIEXPORT jint JNICALL Java_xflaim_Db__1getNextIncBackupSequenceNum
  (JNIEnv *, jobject, jlong);

/*
 * Class:     xflaim_Db
 * Method:    _getDiskSpaceDataSize
 * Signature: (J)J
 */
JNIEXPORT jlong JNICALL Java_xflaim_Db__1getDiskSpaceDataSize
  (JNIEnv *, jobject, jlong);

/*
 * Class:     xflaim_Db
 * Method:    _getDiskSpaceRollbackSize
 * Signature: (J)J
 */
JNIEXPORT jlong JNICALL Java_xflaim_Db__1getDiskSpaceRollbackSize
  (JNIEnv *, jobject, jlong);

/*
 * Class:     xflaim_Db
 * Method:    _getDiskSpaceRflSize
 * Signature: (J)J
 */
JNIEXPORT jlong JNICALL Java_xflaim_Db__1getDiskSpaceRflSize
  (JNIEnv *, jobject, jlong);

/*
 * Class:     xflaim_Db
 * Method:    _getDiskSpaceTotalSize
 * Signature: (J)J
 */
JNIEXPORT jlong JNICALL Java_xflaim_Db__1getDiskSpaceTotalSize
  (JNIEnv *, jobject, jlong);

/*
 * Class:     xflaim_Db
 * Method:    _getMustCloseRC
 * Signature: (J)I
 */
JNIEXPORT jint JNICALL Java_xflaim_Db__1getMustCloseRC
  (JNIEnv *, jobject, jlong);

/*
 * Class:     xflaim_Db
 * Method:    _getAbortRC
 * Signature: (J)I
 */
JNIEXPORT jint JNICALL Java_xflaim_Db__1getAbortRC
  (JNIEnv *, jobject, jlong);

/*
 * Class:     xflaim_Db
 * Method:    _setMustAbortTrans
 * Signature: (JI)V
 */
JNIEXPORT void JNICALL Java_xflaim_Db__1setMustAbortTrans
  (JNIEnv *, jobject, jlong, jint);

/*
 * Class:     xflaim_Db
 * Method:    _enableEncryption
 * Signature: (J)V
 */
JNIEXPORT void JNICALL Java_xflaim_Db__1enableEncryption
  (JNIEnv *, jobject, jlong);

/*
 * Class:     xflaim_Db
 * Method:    _wrapKey
 * Signature: (JLjava/lang/String;)V
 */
JNIEXPORT void JNICALL Java_xflaim_Db__1wrapKey
  (JNIEnv *, jobject, jlong, jstring);

/*
 * Class:     xflaim_Db
 * Method:    _rollOverDbKey
 * Signature: (J)V
 */
JNIEXPORT void JNICALL Java_xflaim_Db__1rollOverDbKey
  (JNIEnv *, jobject, jlong);

/*
 * Class:     xflaim_Db
 * Method:    _getSerialNumber
 * Signature: (J)[B
 */
JNIEXPORT jbyteArray JNICALL Java_xflaim_Db__1getSerialNumber
  (JNIEnv *, jobject, jlong);

/*
 * Class:     xflaim_Db
 * Method:    _getCheckpointInfo
 * Signature: (J)Lxflaim/CheckpointInfo;
 */
JNIEXPORT jobject JNICALL Java_xflaim_Db__1getCheckpointInfo
  (JNIEnv *, jobject, jlong);

/*
 * Class:     xflaim_Db
 * Method:    _exportXML
 * Signature: (JJLjava/lang/String;I)V
 */
JNIEXPORT void JNICALL Java_xflaim_Db__1exportXML__JJLjava_lang_String_2I
  (JNIEnv *, jobject, jlong, jlong, jstring, jint);

/*
 * Class:     xflaim_Db
 * Method:    _exportXML
 * Signature: (JJI)Ljava/lang/String;
 */
JNIEXPORT jstring JNICALL Java_xflaim_Db__1exportXML__JJI
  (JNIEnv *, jobject, jlong, jlong, jint);

/*
 * Class:     xflaim_Db
 * Method:    _getLockWaiters
 * Signature: (J)[Lxflaim/LockUser;
 */
JNIEXPORT jobjectArray JNICALL Java_xflaim_Db__1getLockWaiters
  (JNIEnv *, jobject, jlong);

/*
 * Class:     xflaim_Db
 * Method:    _setDeleteStatusObject
 * Signature: (JLxflaim/DeleteStatus;)V
 */
JNIEXPORT void JNICALL Java_xflaim_Db__1setDeleteStatusObject
  (JNIEnv *, jobject, jlong, jobject);

/*
 * Class:     xflaim_Db
 * Method:    _setIndexingClientObject
 * Signature: (JLxflaim/IxClient;)V
 */
JNIEXPORT void JNICALL Java_xflaim_Db__1setIndexingClientObject
  (JNIEnv *, jobject, jlong, jobject);

/*
 * Class:     xflaim_Db
 * Method:    _setIndexingStatusObject
 * Signature: (JLxflaim/IxStatus;)V
 */
JNIEXPORT void JNICALL Java_xflaim_Db__1setIndexingStatusObject
  (JNIEnv *, jobject, jlong, jobject);

/*
 * Class:     xflaim_Db
 * Method:    _setCommitClientObject
 * Signature: (JLxflaim/CommitClient;)V
 */
JNIEXPORT void JNICALL Java_xflaim_Db__1setCommitClientObject
  (JNIEnv *, jobject, jlong, jobject);

/*
 * Class:     xflaim_Db
 * Method:    _upgrade
 * Signature: (J)V
 */
JNIEXPORT void JNICALL Java_xflaim_Db__1upgrade
  (JNIEnv *, jobject, jlong);

#ifdef __cplusplus
}
#endif
#endif
