/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class xflaim_RebuildStatus */

#ifndef _Included_xflaim_RebuildStatus
#define _Included_xflaim_RebuildStatus
#ifdef __cplusplus
extern "C" {
#endif
#ifdef __cplusplus
}
#endif
#endif
