/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class xflaim_KeyRetrieveFlags */

#ifndef _Included_xflaim_KeyRetrieveFlags
#define _Included_xflaim_KeyRetrieveFlags
#ifdef __cplusplus
extern "C" {
#endif
#undef xflaim_KeyRetrieveFlags_FO_INCL
#define xflaim_KeyRetrieveFlags_FO_INCL 16L
#undef xflaim_KeyRetrieveFlags_FO_EXCL
#define xflaim_KeyRetrieveFlags_FO_EXCL 32L
#undef xflaim_KeyRetrieveFlags_FO_EXACT
#define xflaim_KeyRetrieveFlags_FO_EXACT 64L
#undef xflaim_KeyRetrieveFlags_FO_KEY_EXACT
#define xflaim_KeyRetrieveFlags_FO_KEY_EXACT 128L
#undef xflaim_KeyRetrieveFlags_FO_FIRST
#define xflaim_KeyRetrieveFlags_FO_FIRST 256L
#undef xflaim_KeyRetrieveFlags_FO_LAST
#define xflaim_KeyRetrieveFlags_FO_LAST 512L
#undef xflaim_KeyRetrieveFlags_FO_MATCH_IDS
#define xflaim_KeyRetrieveFlags_FO_MATCH_IDS 1024L
#ifdef __cplusplus
}
#endif
#endif
