/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class xflaim_DefaultBackupClient */

#ifndef _Included_xflaim_DefaultBackupClient
#define _Included_xflaim_DefaultBackupClient
#ifdef __cplusplus
extern "C" {
#endif
#ifdef __cplusplus
}
#endif
#endif
