/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class xflaim_DbInfo */

#ifndef _Included_xflaim_DbInfo
#define _Included_xflaim_DbInfo
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     xflaim_DbInfo
 * Method:    _release
 * Signature: (J)V
 */
JNIEXPORT void JNICALL Java_xflaim_DbInfo__1release
  (JNIEnv *, jobject, jlong);

#ifdef __cplusplus
}
#endif
#endif
