/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class xflaim_BackupStatus */

#ifndef _Included_xflaim_BackupStatus
#define _Included_xflaim_BackupStatus
#ifdef __cplusplus
extern "C" {
#endif
#ifdef __cplusplus
}
#endif
#endif
