/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class xflaim_ReserveID */

#ifndef _Included_xflaim_ReserveID
#define _Included_xflaim_ReserveID
#ifdef __cplusplus
extern "C" {
#endif
#undef xflaim_ReserveID_ELM_ELEMENT_TAG
#define xflaim_ReserveID_ELM_ELEMENT_TAG -512L
#undef xflaim_ReserveID_ELM_ATTRIBUTE_TAG
#define xflaim_ReserveID_ELM_ATTRIBUTE_TAG -511L
#undef xflaim_ReserveID_ELM_INDEX_TAG
#define xflaim_ReserveID_ELM_INDEX_TAG -510L
#undef xflaim_ReserveID_ELM_ELEMENT_COMPONENT_TAG
#define xflaim_ReserveID_ELM_ELEMENT_COMPONENT_TAG -508L
#undef xflaim_ReserveID_ELM_ATTRIBUTE_COMPONENT_TAG
#define xflaim_ReserveID_ELM_ATTRIBUTE_COMPONENT_TAG -507L
#undef xflaim_ReserveID_ELM_COLLECTION_TAG
#define xflaim_ReserveID_ELM_COLLECTION_TAG -506L
#undef xflaim_ReserveID_ELM_PREFIX_TAG
#define xflaim_ReserveID_ELM_PREFIX_TAG -505L
#undef xflaim_ReserveID_ELM_NEXT_DICT_NUMS_TAG
#define xflaim_ReserveID_ELM_NEXT_DICT_NUMS_TAG -504L
#undef xflaim_ReserveID_ELM_DOCUMENT_TITLE_TAG
#define xflaim_ReserveID_ELM_DOCUMENT_TITLE_TAG -503L
#undef xflaim_ReserveID_ELM_INVALID_TAG
#define xflaim_ReserveID_ELM_INVALID_TAG -502L
#undef xflaim_ReserveID_ELM_QUARANTINED_TAG
#define xflaim_ReserveID_ELM_QUARANTINED_TAG -501L
#undef xflaim_ReserveID_ELM_ALL_TAG
#define xflaim_ReserveID_ELM_ALL_TAG -500L
#undef xflaim_ReserveID_ELM_ANNOTATION_TAG
#define xflaim_ReserveID_ELM_ANNOTATION_TAG -499L
#undef xflaim_ReserveID_ELM_ANY_TAG
#define xflaim_ReserveID_ELM_ANY_TAG -498L
#undef xflaim_ReserveID_ELM_ATTRIBUTE_GROUP_TAG
#define xflaim_ReserveID_ELM_ATTRIBUTE_GROUP_TAG -497L
#undef xflaim_ReserveID_ELM_CHOICE_TAG
#define xflaim_ReserveID_ELM_CHOICE_TAG -496L
#undef xflaim_ReserveID_ELM_COMPLEX_CONTENT_TAG
#define xflaim_ReserveID_ELM_COMPLEX_CONTENT_TAG -495L
#undef xflaim_ReserveID_ELM_COMPLEX_TYPE_TAG
#define xflaim_ReserveID_ELM_COMPLEX_TYPE_TAG -494L
#undef xflaim_ReserveID_ELM_DOCUMENTATION_TAG
#define xflaim_ReserveID_ELM_DOCUMENTATION_TAG -493L
#undef xflaim_ReserveID_ELM_ENUMERATION_TAG
#define xflaim_ReserveID_ELM_ENUMERATION_TAG -492L
#undef xflaim_ReserveID_ELM_EXTENSION_TAG
#define xflaim_ReserveID_ELM_EXTENSION_TAG -491L
#undef xflaim_ReserveID_ELM_GROUP_TAG
#define xflaim_ReserveID_ELM_GROUP_TAG -490L
#undef xflaim_ReserveID_ELM_MAX_OCCURS_TAG
#define xflaim_ReserveID_ELM_MAX_OCCURS_TAG -489L
#undef xflaim_ReserveID_ELM_MIN_OCCURS_TAG
#define xflaim_ReserveID_ELM_MIN_OCCURS_TAG -488L
#undef xflaim_ReserveID_ELM_RESTRICTION_TAG
#define xflaim_ReserveID_ELM_RESTRICTION_TAG -487L
#undef xflaim_ReserveID_ELM_SEQUENCE_TAG
#define xflaim_ReserveID_ELM_SEQUENCE_TAG -486L
#undef xflaim_ReserveID_ELM_SIMPLE_CONTENT_TAG
#define xflaim_ReserveID_ELM_SIMPLE_CONTENT_TAG -485L
#undef xflaim_ReserveID_ELM_ROOT_TAG
#define xflaim_ReserveID_ELM_ROOT_TAG -511L
#undef xflaim_ReserveID_ATTR_DICT_NUMBER_TAG
#define xflaim_ReserveID_ATTR_DICT_NUMBER_TAG -512L
#undef xflaim_ReserveID_ATTR_COLLECTION_NUMBER_TAG
#define xflaim_ReserveID_ATTR_COLLECTION_NUMBER_TAG -511L
#undef xflaim_ReserveID_ATTR_COLLECTION_NAME_TAG
#define xflaim_ReserveID_ATTR_COLLECTION_NAME_TAG -510L
#undef xflaim_ReserveID_ATTR_NAME_TAG
#define xflaim_ReserveID_ATTR_NAME_TAG -509L
#undef xflaim_ReserveID_ATTR_TARGET_NAMESPACE_TAG
#define xflaim_ReserveID_ATTR_TARGET_NAMESPACE_TAG -508L
#undef xflaim_ReserveID_ATTR_TYPE_TAG
#define xflaim_ReserveID_ATTR_TYPE_TAG -507L
#undef xflaim_ReserveID_ATTR_STATE_TAG
#define xflaim_ReserveID_ATTR_STATE_TAG -506L
#undef xflaim_ReserveID_ATTR_LANGUAGE_TAG
#define xflaim_ReserveID_ATTR_LANGUAGE_TAG -505L
#undef xflaim_ReserveID_ATTR_INDEX_OPTIONS_TAG
#define xflaim_ReserveID_ATTR_INDEX_OPTIONS_TAG -504L
#undef xflaim_ReserveID_ATTR_INDEX_ON_TAG
#define xflaim_ReserveID_ATTR_INDEX_ON_TAG -503L
#undef xflaim_ReserveID_ATTR_REQUIRED_TAG
#define xflaim_ReserveID_ATTR_REQUIRED_TAG -502L
#undef xflaim_ReserveID_ATTR_LIMIT_TAG
#define xflaim_ReserveID_ATTR_LIMIT_TAG -501L
#undef xflaim_ReserveID_ATTR_COMPARE_RULES_TAG
#define xflaim_ReserveID_ATTR_COMPARE_RULES_TAG -500L
#undef xflaim_ReserveID_ATTR_KEY_COMPONENT_TAG
#define xflaim_ReserveID_ATTR_KEY_COMPONENT_TAG -499L
#undef xflaim_ReserveID_ATTR_DATA_COMPONENT_TAG
#define xflaim_ReserveID_ATTR_DATA_COMPONENT_TAG -498L
#undef xflaim_ReserveID_ATTR_LAST_DOC_INDEXED_TAG
#define xflaim_ReserveID_ATTR_LAST_DOC_INDEXED_TAG -497L
#undef xflaim_ReserveID_ATTR_NEXT_ELEMENT_NUM_TAG
#define xflaim_ReserveID_ATTR_NEXT_ELEMENT_NUM_TAG -496L
#undef xflaim_ReserveID_ATTR_NEXT_ATTRIBUTE_NUM_TAG
#define xflaim_ReserveID_ATTR_NEXT_ATTRIBUTE_NUM_TAG -495L
#undef xflaim_ReserveID_ATTR_NEXT_INDEX_NUM_TAG
#define xflaim_ReserveID_ATTR_NEXT_INDEX_NUM_TAG -494L
#undef xflaim_ReserveID_ATTR_NEXT_COLLECTION_NUM_TAG
#define xflaim_ReserveID_ATTR_NEXT_COLLECTION_NUM_TAG -493L
#undef xflaim_ReserveID_ATTR_NEXT_PREFIX_NUM_TAG
#define xflaim_ReserveID_ATTR_NEXT_PREFIX_NUM_TAG -492L
#undef xflaim_ReserveID_ATTR_DEFAULT_PREFIX_TAG
#define xflaim_ReserveID_ATTR_DEFAULT_PREFIX_TAG -491L
#undef xflaim_ReserveID_ATTR_SOURCE_TAG
#define xflaim_ReserveID_ATTR_SOURCE_TAG -490L
#undef xflaim_ReserveID_ATTR_STATE_CHANGE_COUNT_TAG
#define xflaim_ReserveID_ATTR_STATE_CHANGE_COUNT_TAG -489L
#undef xflaim_ReserveID_ATTR_XMLNS_TAG
#define xflaim_ReserveID_ATTR_XMLNS_TAG -488L
#undef xflaim_ReserveID_ATTR_ABSTRACT_TAG
#define xflaim_ReserveID_ATTR_ABSTRACT_TAG -487L
#undef xflaim_ReserveID_ATTR_BASE_TAG
#define xflaim_ReserveID_ATTR_BASE_TAG -486L
#undef xflaim_ReserveID_ATTR_BLOCK_TAG
#define xflaim_ReserveID_ATTR_BLOCK_TAG -485L
#undef xflaim_ReserveID_ATTR_DEFAULT_TAG
#define xflaim_ReserveID_ATTR_DEFAULT_TAG -484L
#undef xflaim_ReserveID_ATTR_FINAL_TAG
#define xflaim_ReserveID_ATTR_FINAL_TAG -483L
#undef xflaim_ReserveID_ATTR_FIXED_TAG
#define xflaim_ReserveID_ATTR_FIXED_TAG -482L
#undef xflaim_ReserveID_ATTR_ITEM_TYPE_TAG
#define xflaim_ReserveID_ATTR_ITEM_TYPE_TAG -481L
#undef xflaim_ReserveID_ATTR_MAX_OCCURS_TAG
#define xflaim_ReserveID_ATTR_MAX_OCCURS_TAG -480L
#undef xflaim_ReserveID_ATTR_MEMBER_TYPES_TAG
#define xflaim_ReserveID_ATTR_MEMBER_TYPES_TAG -479L
#undef xflaim_ReserveID_ATTR_MIN_OCCURS_TAG
#define xflaim_ReserveID_ATTR_MIN_OCCURS_TAG -478L
#undef xflaim_ReserveID_ATTR_MIXED_TAG
#define xflaim_ReserveID_ATTR_MIXED_TAG -477L
#undef xflaim_ReserveID_ATTR_NILLABLE_TAG
#define xflaim_ReserveID_ATTR_NILLABLE_TAG -476L
#undef xflaim_ReserveID_ATTR_REF_TAG
#define xflaim_ReserveID_ATTR_REF_TAG -475L
#undef xflaim_ReserveID_ATTR_USE_TAG
#define xflaim_ReserveID_ATTR_USE_TAG -474L
#undef xflaim_ReserveID_ATTR_VALUE_TAG
#define xflaim_ReserveID_ATTR_VALUE_TAG -473L
#undef xflaim_ReserveID_XS_PREFIX_ID
#define xflaim_ReserveID_XS_PREFIX_ID -512L
#undef xflaim_ReserveID_XSI_PREFIX_ID
#define xflaim_ReserveID_XSI_PREFIX_ID -511L
#undef xflaim_ReserveID_XFLAIM_PREFIX_ID
#define xflaim_ReserveID_XFLAIM_PREFIX_ID -510L
#undef xflaim_ReserveID_XMLNS_PREFIX_ID
#define xflaim_ReserveID_XMLNS_PREFIX_ID -509L
#ifdef __cplusplus
}
#endif
#endif
