/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class xflaim_Query */

#ifndef _Included_xflaim_Query
#define _Included_xflaim_Query
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     xflaim_Query
 * Method:    _release
 * Signature: (J)V
 */
JNIEXPORT void JNICALL Java_xflaim_Query__1release
  (JNIEnv *, jobject, jlong);

/*
 * Class:     xflaim_Query
 * Method:    _createQuery
 * Signature: (I)J
 */
JNIEXPORT jlong JNICALL Java_xflaim_Query__1createQuery
  (JNIEnv *, jobject, jint);

/*
 * Class:     xflaim_Query
 * Method:    _setLanguage
 * Signature: (JI)V
 */
JNIEXPORT void JNICALL Java_xflaim_Query__1setLanguage
  (JNIEnv *, jobject, jlong, jint);

/*
 * Class:     xflaim_Query
 * Method:    _setupQueryExpr
 * Signature: (JJLjava/lang/String;)V
 */
JNIEXPORT void JNICALL Java_xflaim_Query__1setupQueryExpr
  (JNIEnv *, jobject, jlong, jlong, jstring);

/*
 * Class:     xflaim_Query
 * Method:    _copyCriteria
 * Signature: (JJ)V
 */
JNIEXPORT void JNICALL Java_xflaim_Query__1copyCriteria
  (JNIEnv *, jobject, jlong, jlong);

/*
 * Class:     xflaim_Query
 * Method:    _addXPathComponent
 * Signature: (JIII)V
 */
JNIEXPORT void JNICALL Java_xflaim_Query__1addXPathComponent
  (JNIEnv *, jobject, jlong, jint, jint, jint);

/*
 * Class:     xflaim_Query
 * Method:    _addOperator
 * Signature: (JI)V
 */
JNIEXPORT void JNICALL Java_xflaim_Query__1addOperator
  (JNIEnv *, jobject, jlong, jint);

/*
 * Class:     xflaim_Query
 * Method:    _addStringOperator
 * Signature: (JIZZZZZZZZ)V
 */
JNIEXPORT void JNICALL Java_xflaim_Query__1addStringOperator
  (JNIEnv *, jobject, jlong, jint, jboolean, jboolean, jboolean, jboolean, jboolean, jboolean, jboolean, jboolean);

/*
 * Class:     xflaim_Query
 * Method:    _addStringValue
 * Signature: (JLjava/lang/String;)V
 */
JNIEXPORT void JNICALL Java_xflaim_Query__1addStringValue
  (JNIEnv *, jobject, jlong, jstring);

/*
 * Class:     xflaim_Query
 * Method:    _addBinaryValue
 * Signature: (J[B)V
 */
JNIEXPORT void JNICALL Java_xflaim_Query__1addBinaryValue
  (JNIEnv *, jobject, jlong, jbyteArray);

/*
 * Class:     xflaim_Query
 * Method:    _addLongValue
 * Signature: (JJ)V
 */
JNIEXPORT void JNICALL Java_xflaim_Query__1addLongValue
  (JNIEnv *, jobject, jlong, jlong);

/*
 * Class:     xflaim_Query
 * Method:    _addBoolean
 * Signature: (JZZ)V
 */
JNIEXPORT void JNICALL Java_xflaim_Query__1addBoolean
  (JNIEnv *, jobject, jlong, jboolean, jboolean);

#ifdef __cplusplus
}
#endif
#endif
