/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class xflaim_CacheInfo */

#ifndef _Included_xflaim_CacheInfo
#define _Included_xflaim_CacheInfo
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     xflaim_CacheInfo
 * Method:    initIDs
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_xflaim_CacheInfo_initIDs
  (JNIEnv *, jclass);

#ifdef __cplusplus
}
#endif
#endif
