/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class xflaim_CORRUPTINFO */

#ifndef _Included_xflaim_CORRUPTINFO
#define _Included_xflaim_CORRUPTINFO
#ifdef __cplusplus
extern "C" {
#endif
#ifdef __cplusplus
}
#endif
#endif
