/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class xflaim_FlmBackupType */

#ifndef _Included_xflaim_FlmBackupType
#define _Included_xflaim_FlmBackupType
#ifdef __cplusplus
extern "C" {
#endif
#undef xflaim_FlmBackupType_FULL_BACKUP
#define xflaim_FlmBackupType_FULL_BACKUP 0L
#undef xflaim_FlmBackupType_INCREMENTAL_BACKUP
#define xflaim_FlmBackupType_INCREMENTAL_BACKUP 1L
#ifdef __cplusplus
}
#endif
#endif
