/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class xflaim_DbCheckFlags */

#ifndef _Included_xflaim_DbCheckFlags
#define _Included_xflaim_DbCheckFlags
#ifdef __cplusplus
extern "C" {
#endif
#undef xflaim_DbCheckFlags_FO_ONLINE
#define xflaim_DbCheckFlags_FO_ONLINE 32L
#undef xflaim_DbCheckFlags_FO_DO_LOGICAL_CHECK
#define xflaim_DbCheckFlags_FO_DO_LOGICAL_CHECK 256L
#undef xflaim_DbCheckFlags_FO_SKIP_DOM_LINK_CHECK
#define xflaim_DbCheckFlags_FO_SKIP_DOM_LINK_CHECK 1024L
#ifdef __cplusplus
}
#endif
#endif
