/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class xflaim_Backup */

#ifndef _Included_xflaim_Backup
#define _Included_xflaim_Backup
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     xflaim_Backup
 * Method:    _backup
 * Signature: (JLjava/lang/String;Ljava/lang/String;Lxflaim/BackupClient;Lxflaim/BackupStatus;)J
 */
JNIEXPORT jlong JNICALL Java_xflaim_Backup__1backup
  (JNIEnv *, jobject, jlong, jstring, jstring, jobject, jobject);

/*
 * Class:     xflaim_Backup
 * Method:    _endBackup
 * Signature: (J)V
 */
JNIEXPORT void JNICALL Java_xflaim_Backup__1endBackup
  (JNIEnv *, jobject, jlong);

/*
 * Class:     xflaim_Backup
 * Method:    _getBackupTransId
 * Signature: (J)J
 */
JNIEXPORT jlong JNICALL Java_xflaim_Backup__1getBackupTransId
  (JNIEnv *, jobject, jlong);

/*
 * Class:     xflaim_Backup
 * Method:    _getLastBackupTransId
 * Signature: (J)J
 */
JNIEXPORT jlong JNICALL Java_xflaim_Backup__1getLastBackupTransId
  (JNIEnv *, jobject, jlong);

/*
 * Class:     xflaim_Backup
 * Method:    _release
 * Signature: (J)V
 */
JNIEXPORT void JNICALL Java_xflaim_Backup__1release
  (JNIEnv *, jobject, jlong);

#ifdef __cplusplus
}
#endif
#endif
