/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class xflaim_RestoreAction */

#ifndef _Included_xflaim_RestoreAction
#define _Included_xflaim_RestoreAction
#ifdef __cplusplus
extern "C" {
#endif
#undef xflaim_RestoreAction_CONTINUE
#define xflaim_RestoreAction_CONTINUE 0L
#undef xflaim_RestoreAction_STOP
#define xflaim_RestoreAction_STOP 1L
#undef xflaim_RestoreAction_SKIP
#define xflaim_RestoreAction_SKIP 2L
#undef xflaim_RestoreAction_RETRY
#define xflaim_RestoreAction_RETRY 3L
#ifdef __cplusplus
}
#endif
#endif
