/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class xflaim_FlmDataType */

#ifndef _Included_xflaim_FlmDataType
#define _Included_xflaim_FlmDataType
#ifdef __cplusplus
extern "C" {
#endif
#undef xflaim_FlmDataType_FLM_NODATA_TYPE
#define xflaim_FlmDataType_FLM_NODATA_TYPE 0L
#undef xflaim_FlmDataType_FLM_TEXT_TYPE
#define xflaim_FlmDataType_FLM_TEXT_TYPE 1L
#undef xflaim_FlmDataType_FLM_NUMBER_TYPE
#define xflaim_FlmDataType_FLM_NUMBER_TYPE 2L
#undef xflaim_FlmDataType_FLM_BINARY_TYPE
#define xflaim_FlmDataType_FLM_BINARY_TYPE 3L
#undef xflaim_FlmDataType_FLM_NUM_OF_TYPES
#define xflaim_FlmDataType_FLM_NUM_OF_TYPES 4L
#undef xflaim_FlmDataType_FLM_UNKNOWN_TYPE
#define xflaim_FlmDataType_FLM_UNKNOWN_TYPE 15L
#ifdef __cplusplus
}
#endif
#endif
