/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class xflaim_BlockIOStats */

#ifndef _Included_xflaim_BlockIOStats
#define _Included_xflaim_BlockIOStats
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     xflaim_BlockIOStats
 * Method:    initIDs
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_xflaim_BlockIOStats_initIDs
  (JNIEnv *, jclass);

#ifdef __cplusplus
}
#endif
#endif
