/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class xflaim_OptInfo */

#ifndef _Included_xflaim_OptInfo
#define _Included_xflaim_OptInfo
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     xflaim_OptInfo
 * Method:    initIDs
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_xflaim_OptInfo_initIDs
  (JNIEnv *, jclass);

#ifdef __cplusplus
}
#endif
#endif
