/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class xflaim_RestoreClient */

#ifndef _Included_xflaim_RestoreClient
#define _Included_xflaim_RestoreClient
#ifdef __cplusplus
extern "C" {
#endif
#ifdef __cplusplus
}
#endif
#endif
