/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class xflaim_DeleteStatus */

#ifndef _Included_xflaim_DeleteStatus
#define _Included_xflaim_DeleteStatus
#ifdef __cplusplus
extern "C" {
#endif
#ifdef __cplusplus
}
#endif
#endif
