/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class xflaim_PosIStream */

#ifndef _Included_xflaim_PosIStream
#define _Included_xflaim_PosIStream
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     xflaim_PosIStream
 * Method:    _release
 * Signature: (J)V
 */
JNIEXPORT void JNICALL Java_xflaim_PosIStream__1release
  (JNIEnv *, jobject, jlong);

#ifdef __cplusplus
}
#endif
#endif
