/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class xflaim_IndexState */

#ifndef _Included_xflaim_IndexState
#define _Included_xflaim_IndexState
#ifdef __cplusplus
extern "C" {
#endif
#undef xflaim_IndexState_XFLM_INDEX_ONLINE
#define xflaim_IndexState_XFLM_INDEX_ONLINE 0L
#undef xflaim_IndexState_XFLM_INDEX_BRINGING_ONLINE
#define xflaim_IndexState_XFLM_INDEX_BRINGING_ONLINE 1L
#undef xflaim_IndexState_XFLM_INDEX_SUSPENDED
#define xflaim_IndexState_XFLM_INDEX_SUSPENDED 2L
#ifdef __cplusplus
}
#endif
#endif
