/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class xflaim_DbSystem */

#ifndef _Included_xflaim_DbSystem
#define _Included_xflaim_DbSystem
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     xflaim_DbSystem
 * Method:    _createDbSystem
 * Signature: ()J
 */
JNIEXPORT jlong JNICALL Java_xflaim_DbSystem__1createDbSystem
  (JNIEnv *, jobject);

/*
 * Class:     xflaim_DbSystem
 * Method:    _init
 * Signature: (J)V
 */
JNIEXPORT void JNICALL Java_xflaim_DbSystem__1init
  (JNIEnv *, jobject, jlong);

/*
 * Class:     xflaim_DbSystem
 * Method:    _exit
 * Signature: (J)V
 */
JNIEXPORT void JNICALL Java_xflaim_DbSystem__1exit
  (JNIEnv *, jobject, jlong);

/*
 * Class:     xflaim_DbSystem
 * Method:    _dbCreate
 * Signature: (JLjava/lang/String;Ljava/lang/String;Ljava/lang/String;Ljava/lang/String;Ljava/lang/String;Lxflaim/CREATEOPTS;)J
 */
JNIEXPORT jlong JNICALL Java_xflaim_DbSystem__1dbCreate
  (JNIEnv *, jobject, jlong, jstring, jstring, jstring, jstring, jstring, jobject);

/*
 * Class:     xflaim_DbSystem
 * Method:    _dbOpen
 * Signature: (JLjava/lang/String;Ljava/lang/String;Ljava/lang/String;Ljava/lang/String;Z)J
 */
JNIEXPORT jlong JNICALL Java_xflaim_DbSystem__1dbOpen
  (JNIEnv *, jobject, jlong, jstring, jstring, jstring, jstring, jboolean);

/*
 * Class:     xflaim_DbSystem
 * Method:    _dbRemove
 * Signature: (JLjava/lang/String;Ljava/lang/String;Ljava/lang/String;Z)V
 */
JNIEXPORT void JNICALL Java_xflaim_DbSystem__1dbRemove
  (JNIEnv *, jobject, jlong, jstring, jstring, jstring, jboolean);

/*
 * Class:     xflaim_DbSystem
 * Method:    _dbCheck
 * Signature: (JLjava/lang/String;Ljava/lang/String;Ljava/lang/String;Ljava/lang/String;ILxflaim/DbCheckStatus;)J
 */
JNIEXPORT jlong JNICALL Java_xflaim_DbSystem__1dbCheck
  (JNIEnv *, jobject, jlong, jstring, jstring, jstring, jstring, jint, jobject);

/*
 * Class:     xflaim_DbSystem
 * Method:    _dbCopy
 * Signature: (JLjava/lang/String;Ljava/lang/String;Ljava/lang/String;Ljava/lang/String;Ljava/lang/String;Ljava/lang/String;Lxflaim/DbCopyStatus;)V
 */
JNIEXPORT void JNICALL Java_xflaim_DbSystem__1dbCopy
  (JNIEnv *, jobject, jlong, jstring, jstring, jstring, jstring, jstring, jstring, jobject);

/*
 * Class:     xflaim_DbSystem
 * Method:    _dbRestore
 * Signature: (JLjava/lang/String;Ljava/lang/String;Ljava/lang/String;Ljava/lang/String;Ljava/lang/String;Lxflaim/RestoreClient;Lxflaim/RestoreStatus;)V
 */
JNIEXPORT void JNICALL Java_xflaim_DbSystem__1dbRestore
  (JNIEnv *, jobject, jlong, jstring, jstring, jstring, jstring, jstring, jobject, jobject);

/*
 * Class:     xflaim_DbSystem
 * Method:    _dbRename
 * Signature: (JLjava/lang/String;Ljava/lang/String;Ljava/lang/String;Ljava/lang/String;ZLxflaim/DbRenameStatus;)V
 */
JNIEXPORT void JNICALL Java_xflaim_DbSystem__1dbRename
  (JNIEnv *, jobject, jlong, jstring, jstring, jstring, jstring, jboolean, jobject);

/*
 * Class:     xflaim_DbSystem
 * Method:    _openBufferIStream
 * Signature: (JLjava/lang/String;)J
 */
JNIEXPORT jlong JNICALL Java_xflaim_DbSystem__1openBufferIStream
  (JNIEnv *, jobject, jlong, jstring);

/*
 * Class:     xflaim_DbSystem
 * Method:    _openFileIStream
 * Signature: (JLjava/lang/String;)J
 */
JNIEXPORT jlong JNICALL Java_xflaim_DbSystem__1openFileIStream
  (JNIEnv *, jobject, jlong, jstring);

/*
 * Class:     xflaim_DbSystem
 * Method:    _createJDataVector
 * Signature: (J)J
 */
JNIEXPORT jlong JNICALL Java_xflaim_DbSystem__1createJDataVector
  (JNIEnv *, jobject, jlong);

#ifdef __cplusplus
}
#endif
#endif
