/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class xflaim_DbSystem */

#ifndef _Included_xflaim_DbSystem
#define _Included_xflaim_DbSystem
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     xflaim_DbSystem
 * Method:    _createDbSystem
 * Signature: ()J
 */
JNIEXPORT jlong JNICALL Java_xflaim_DbSystem__1createDbSystem
  (JNIEnv *, jobject);

/*
 * Class:     xflaim_DbSystem
 * Method:    _init
 * Signature: (J)V
 */
JNIEXPORT void JNICALL Java_xflaim_DbSystem__1init
  (JNIEnv *, jobject, jlong);

/*
 * Class:     xflaim_DbSystem
 * Method:    _exit
 * Signature: (J)V
 */
JNIEXPORT void JNICALL Java_xflaim_DbSystem__1exit
  (JNIEnv *, jobject, jlong);

/*
 * Class:     xflaim_DbSystem
 * Method:    _dbCreate
 * Signature: (JLjava/lang/String;Ljava/lang/String;Ljava/lang/String;Ljava/lang/String;Ljava/lang/String;Lxflaim/CREATEOPTS;)J
 */
JNIEXPORT jlong JNICALL Java_xflaim_DbSystem__1dbCreate
  (JNIEnv *, jobject, jlong, jstring, jstring, jstring, jstring, jstring, jobject);

/*
 * Class:     xflaim_DbSystem
 * Method:    _dbOpen
 * Signature: (JLjava/lang/String;Ljava/lang/String;Ljava/lang/String;Ljava/lang/String;Z)J
 */
JNIEXPORT jlong JNICALL Java_xflaim_DbSystem__1dbOpen
  (JNIEnv *, jobject, jlong, jstring, jstring, jstring, jstring, jboolean);

/*
 * Class:     xflaim_DbSystem
 * Method:    _dbRemove
 * Signature: (JLjava/lang/String;Ljava/lang/String;Ljava/lang/String;Z)V
 */
JNIEXPORT void JNICALL Java_xflaim_DbSystem__1dbRemove
  (JNIEnv *, jobject, jlong, jstring, jstring, jstring, jboolean);

/*
 * Class:     xflaim_DbSystem
 * Method:    _dbCheck
 * Signature: (JLjava/lang/String;Ljava/lang/String;Ljava/lang/String;Ljava/lang/String;ILxflaim/DbCheckStatus;)J
 */
JNIEXPORT jlong JNICALL Java_xflaim_DbSystem__1dbCheck
  (JNIEnv *, jobject, jlong, jstring, jstring, jstring, jstring, jint, jobject);

/*
 * Class:     xflaim_DbSystem
 * Method:    _dbCopy
 * Signature: (JLjava/lang/String;Ljava/lang/String;Ljava/lang/String;Ljava/lang/String;Ljava/lang/String;Ljava/lang/String;Lxflaim/DbCopyStatus;)V
 */
JNIEXPORT void JNICALL Java_xflaim_DbSystem__1dbCopy
  (JNIEnv *, jobject, jlong, jstring, jstring, jstring, jstring, jstring, jstring, jobject);

/*
 * Class:     xflaim_DbSystem
 * Method:    _dbRestore
 * Signature: (JLjava/lang/String;Ljava/lang/String;Ljava/lang/String;Ljava/lang/String;Ljava/lang/String;Lxflaim/RestoreClient;Lxflaim/RestoreStatus;)V
 */
JNIEXPORT void JNICALL Java_xflaim_DbSystem__1dbRestore
  (JNIEnv *, jobject, jlong, jstring, jstring, jstring, jstring, jstring, jobject, jobject);

/*
 * Class:     xflaim_DbSystem
 * Method:    _dbRename
 * Signature: (JLjava/lang/String;Ljava/lang/String;Ljava/lang/String;Ljava/lang/String;ZLxflaim/DbRenameStatus;)V
 */
JNIEXPORT void JNICALL Java_xflaim_DbSystem__1dbRename
  (JNIEnv *, jobject, jlong, jstring, jstring, jstring, jstring, jboolean, jobject);

/*
 * Class:     xflaim_DbSystem
 * Method:    _openBufferIStream
 * Signature: (JLjava/lang/String;)J
 */
JNIEXPORT jlong JNICALL Java_xflaim_DbSystem__1openBufferIStream
  (JNIEnv *, jobject, jlong, jstring);

/*
 * Class:     xflaim_DbSystem
 * Method:    _openFileIStream
 * Signature: (JLjava/lang/String;)J
 */
JNIEXPORT jlong JNICALL Java_xflaim_DbSystem__1openFileIStream
  (JNIEnv *, jobject, jlong, jstring);

/*
 * Class:     xflaim_DbSystem
 * Method:    _createJDataVector
 * Signature: (J)J
 */
JNIEXPORT jlong JNICALL Java_xflaim_DbSystem__1createJDataVector
  (JNIEnv *, jobject, jlong);

/*
 * Class:     xflaim_DbSystem
 * Method:    _dbRebuild
 * Signature: (JLjava/lang/String;Ljava/lang/String;Ljava/lang/String;Ljava/lang/String;Ljava/lang/String;Ljava/lang/String;Ljava/lang/String;Lxflaim/CREATEOPTS;Lxflaim/RebuildStatus;)V
 */
JNIEXPORT void JNICALL Java_xflaim_DbSystem__1dbRebuild
  (JNIEnv *, jobject, jlong, jstring, jstring, jstring, jstring, jstring, jstring, jstring, jobject, jobject);

/*
 * Class:     xflaim_DbSystem
 * Method:    _updateIniFile
 * Signature: (JLjava/lang/String;Ljava/lang/String;)V
 */
JNIEXPORT void JNICALL Java_xflaim_DbSystem__1updateIniFile
  (JNIEnv *, jobject, jlong, jstring, jstring);

/*
 * Class:     xflaim_DbSystem
 * Method:    _dbDup
 * Signature: (JJ)J
 */
JNIEXPORT jlong JNICALL Java_xflaim_DbSystem__1dbDup
  (JNIEnv *, jobject, jlong, jlong);

/*
 * Class:     xflaim_DbSystem
 * Method:    _openMultiFileIStream
 * Signature: (JLjava/lang/String;Ljava/lang/String;)J
 */
JNIEXPORT jlong JNICALL Java_xflaim_DbSystem__1openMultiFileIStream
  (JNIEnv *, jobject, jlong, jstring, jstring);

/*
 * Class:     xflaim_DbSystem
 * Method:    _openBufferedIStream
 * Signature: (JJI)J
 */
JNIEXPORT jlong JNICALL Java_xflaim_DbSystem__1openBufferedIStream
  (JNIEnv *, jobject, jlong, jlong, jint);

/*
 * Class:     xflaim_DbSystem
 * Method:    _openUncompressingIStream
 * Signature: (JJ)J
 */
JNIEXPORT jlong JNICALL Java_xflaim_DbSystem__1openUncompressingIStream
  (JNIEnv *, jobject, jlong, jlong);

/*
 * Class:     xflaim_DbSystem
 * Method:    _openFileOStream
 * Signature: (JLjava/lang/String;Z)J
 */
JNIEXPORT jlong JNICALL Java_xflaim_DbSystem__1openFileOStream
  (JNIEnv *, jobject, jlong, jstring, jboolean);

/*
 * Class:     xflaim_DbSystem
 * Method:    _openMultiFileOStream
 * Signature: (JLjava/lang/String;Ljava/lang/String;IZ)J
 */
JNIEXPORT jlong JNICALL Java_xflaim_DbSystem__1openMultiFileOStream
  (JNIEnv *, jobject, jlong, jstring, jstring, jint, jboolean);

/*
 * Class:     xflaim_DbSystem
 * Method:    _removeMultiFileStream
 * Signature: (JLjava/lang/String;Ljava/lang/String;)V
 */
JNIEXPORT void JNICALL Java_xflaim_DbSystem__1removeMultiFileStream
  (JNIEnv *, jobject, jlong, jstring, jstring);

/*
 * Class:     xflaim_DbSystem
 * Method:    _openBufferedOStream
 * Signature: (JJI)J
 */
JNIEXPORT jlong JNICALL Java_xflaim_DbSystem__1openBufferedOStream
  (JNIEnv *, jobject, jlong, jlong, jint);

/*
 * Class:     xflaim_DbSystem
 * Method:    _openCompressingOStream
 * Signature: (JJ)J
 */
JNIEXPORT jlong JNICALL Java_xflaim_DbSystem__1openCompressingOStream
  (JNIEnv *, jobject, jlong, jlong);

/*
 * Class:     xflaim_DbSystem
 * Method:    _writeToOStream
 * Signature: (JJJ)V
 */
JNIEXPORT void JNICALL Java_xflaim_DbSystem__1writeToOStream
  (JNIEnv *, jobject, jlong, jlong, jlong);

/*
 * Class:     xflaim_DbSystem
 * Method:    _openBase64Encoder
 * Signature: (JJZ)J
 */
JNIEXPORT jlong JNICALL Java_xflaim_DbSystem__1openBase64Encoder
  (JNIEnv *, jobject, jlong, jlong, jboolean);

/*
 * Class:     xflaim_DbSystem
 * Method:    _openBase64Decoder
 * Signature: (JJ)J
 */
JNIEXPORT jlong JNICALL Java_xflaim_DbSystem__1openBase64Decoder
  (JNIEnv *, jobject, jlong, jlong);

/*
 * Class:     xflaim_DbSystem
 * Method:    _setDynamicMemoryLimit
 * Signature: (JIIII)V
 */
JNIEXPORT void JNICALL Java_xflaim_DbSystem__1setDynamicMemoryLimit
  (JNIEnv *, jobject, jlong, jint, jint, jint, jint);

/*
 * Class:     xflaim_DbSystem
 * Method:    _setHardMemoryLimit
 * Signature: (JIZIIIZ)V
 */
JNIEXPORT void JNICALL Java_xflaim_DbSystem__1setHardMemoryLimit
  (JNIEnv *, jobject, jlong, jint, jboolean, jint, jint, jint, jboolean);

/*
 * Class:     xflaim_DbSystem
 * Method:    _getDynamicCacheSupported
 * Signature: (J)Z
 */
JNIEXPORT jboolean JNICALL Java_xflaim_DbSystem__1getDynamicCacheSupported
  (JNIEnv *, jobject, jlong);

#ifdef __cplusplus
}
#endif
#endif
