/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class xflaim_DbRebuildStatus */

#ifndef _Included_xflaim_DbRebuildStatus
#define _Included_xflaim_DbRebuildStatus
#ifdef __cplusplus
extern "C" {
#endif
#ifdef __cplusplus
}
#endif
#endif
