/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class xflaim_CHECKINFO */

#ifndef _Included_xflaim_CHECKINFO
#define _Included_xflaim_CHECKINFO
#ifdef __cplusplus
extern "C" {
#endif
#ifdef __cplusplus
}
#endif
#endif
