/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class xflaim_DbCheckStatus */

#ifndef _Included_xflaim_DbCheckStatus
#define _Included_xflaim_DbCheckStatus
#ifdef __cplusplus
extern "C" {
#endif
#ifdef __cplusplus
}
#endif
#endif
