/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class xflaim_IStream */

#ifndef _Included_xflaim_IStream
#define _Included_xflaim_IStream
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     xflaim_IStream
 * Method:    _release
 * Signature: (J)V
 */
JNIEXPORT void JNICALL Java_xflaim_IStream__1release
  (JNIEnv *, jobject, jlong);

#ifdef __cplusplus
}
#endif
#endif
