/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class xflaim_RestoreStatus */

#ifndef _Included_xflaim_RestoreStatus
#define _Included_xflaim_RestoreStatus
#ifdef __cplusplus
extern "C" {
#endif
#ifdef __cplusplus
}
#endif
#endif
