/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class xflaim_TransactionFlags */

#ifndef _Included_xflaim_TransactionFlags
#define _Included_xflaim_TransactionFlags
#ifdef __cplusplus
extern "C" {
#endif
#undef xflaim_TransactionFlags_DONT_KILL_TRANS
#define xflaim_TransactionFlags_DONT_KILL_TRANS 1L
#undef xflaim_TransactionFlags_DONT_POISON_CACHE
#define xflaim_TransactionFlags_DONT_POISON_CACHE 2L
#ifdef __cplusplus
}
#endif
#endif
