/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class xflaim_ResultSetCounts */

#ifndef _Included_xflaim_ResultSetCounts
#define _Included_xflaim_ResultSetCounts
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     xflaim_ResultSetCounts
 * Method:    initIDs
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_xflaim_ResultSetCounts_initIDs
  (JNIEnv *, jclass);

#ifdef __cplusplus
}
#endif
#endif
