/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class xflaim_XPathAxis */

#ifndef _Included_xflaim_XPathAxis
#define _Included_xflaim_XPathAxis
#ifdef __cplusplus
extern "C" {
#endif
#undef xflaim_XPathAxis_ROOT_AXIS
#define xflaim_XPathAxis_ROOT_AXIS 0L
#undef xflaim_XPathAxis_CHILD_AXIS
#define xflaim_XPathAxis_CHILD_AXIS 1L
#undef xflaim_XPathAxis_PARENT_AXIS
#define xflaim_XPathAxis_PARENT_AXIS 2L
#undef xflaim_XPathAxis_ANCESTOR_AXIS
#define xflaim_XPathAxis_ANCESTOR_AXIS 3L
#undef xflaim_XPathAxis_DESCENDANT_AXIS
#define xflaim_XPathAxis_DESCENDANT_AXIS 4L
#undef xflaim_XPathAxis_FOLLOWING_SIBLING_AXIS
#define xflaim_XPathAxis_FOLLOWING_SIBLING_AXIS 5L
#undef xflaim_XPathAxis_PRECEDING_SIBLING_AXIS
#define xflaim_XPathAxis_PRECEDING_SIBLING_AXIS 6L
#undef xflaim_XPathAxis_FOLLOWING_AXIS
#define xflaim_XPathAxis_FOLLOWING_AXIS 7L
#undef xflaim_XPathAxis_PRECEDING_AXIS
#define xflaim_XPathAxis_PRECEDING_AXIS 8L
#undef xflaim_XPathAxis_ATTRIBUTE_AXIS
#define xflaim_XPathAxis_ATTRIBUTE_AXIS 9L
#undef xflaim_XPathAxis_NAMESPACE_AXIS
#define xflaim_XPathAxis_NAMESPACE_AXIS 10L
#undef xflaim_XPathAxis_SELF_AXIS
#define xflaim_XPathAxis_SELF_AXIS 11L
#undef xflaim_XPathAxis_DESCENDANT_OR_SELF_AXIS
#define xflaim_XPathAxis_DESCENDANT_OR_SELF_AXIS 12L
#undef xflaim_XPathAxis_ANCESTOR_OR_SELF_AXIS
#define xflaim_XPathAxis_ANCESTOR_OR_SELF_AXIS 13L
#undef xflaim_XPathAxis_META_AXIS
#define xflaim_XPathAxis_META_AXIS 14L
#ifdef __cplusplus
}
#endif
#endif
