/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class xflaim_SearchFlags */

#ifndef _Included_xflaim_SearchFlags
#define _Included_xflaim_SearchFlags
#ifdef __cplusplus
extern "C" {
#endif
#undef xflaim_SearchFlags_XFLM_INCL
#define xflaim_SearchFlags_XFLM_INCL 16L
#undef xflaim_SearchFlags_XFLM_EXCL
#define xflaim_SearchFlags_XFLM_EXCL 32L
#undef xflaim_SearchFlags_XFLM_EXACT
#define xflaim_SearchFlags_XFLM_EXACT 64L
#undef xflaim_SearchFlags_XFLM_KEY_EXACT
#define xflaim_SearchFlags_XFLM_KEY_EXACT 128L
#undef xflaim_SearchFlags_XFLM_FIRST
#define xflaim_SearchFlags_XFLM_FIRST 256L
#undef xflaim_SearchFlags_XFLM_LAST
#define xflaim_SearchFlags_XFLM_LAST 512L
#undef xflaim_SearchFlags_XFLM_MATCH_IDS
#define xflaim_SearchFlags_XFLM_MATCH_IDS 1024L
#undef xflaim_SearchFlags_XFLM_MATCH_DOC_ID
#define xflaim_SearchFlags_XFLM_MATCH_DOC_ID 2048L
#ifdef __cplusplus
}
#endif
#endif
