/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class xflaim_Collections */

#ifndef _Included_xflaim_Collections
#define _Included_xflaim_Collections
#ifdef __cplusplus
extern "C" {
#endif
#undef xflaim_Collections_DATA
#define xflaim_Collections_DATA 65534L
#undef xflaim_Collections_DICTIONARY
#define xflaim_Collections_DICTIONARY 65535L
#ifdef __cplusplus
}
#endif
#endif
