/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class xflaim_RTransStats */

#ifndef _Included_xflaim_RTransStats
#define _Included_xflaim_RTransStats
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     xflaim_RTransStats
 * Method:    initIDs
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_xflaim_RTransStats_initIDs
  (JNIEnv *, jclass);

#ifdef __cplusplus
}
#endif
#endif
