/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class xflaim_CheckpointInfo */

#ifndef _Included_xflaim_CheckpointInfo
#define _Included_xflaim_CheckpointInfo
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     xflaim_CheckpointInfo
 * Method:    initIDs
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_xflaim_CheckpointInfo_initIDs
  (JNIEnv *, jclass);

#ifdef __cplusplus
}
#endif
#endif
