/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class xflaim_LockUser */

#ifndef _Included_xflaim_LockUser
#define _Included_xflaim_LockUser
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     xflaim_LockUser
 * Method:    initIDs
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_xflaim_LockUser_initIDs
  (JNIEnv *, jclass);

#ifdef __cplusplus
}
#endif
#endif
