/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class xflaim_TransactionType */

#ifndef _Included_xflaim_TransactionType
#define _Included_xflaim_TransactionType
#ifdef __cplusplus
extern "C" {
#endif
#undef xflaim_TransactionType_NO_TRANS
#define xflaim_TransactionType_NO_TRANS 0L
#undef xflaim_TransactionType_READ_TRANS
#define xflaim_TransactionType_READ_TRANS 1L
#undef xflaim_TransactionType_UPDATE_TRANS
#define xflaim_TransactionType_UPDATE_TRANS 2L
#ifdef __cplusplus
}
#endif
#endif
