/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class xflaim_UTransStats */

#ifndef _Included_xflaim_UTransStats
#define _Included_xflaim_UTransStats
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     xflaim_UTransStats
 * Method:    initIDs
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_xflaim_UTransStats_initIDs
  (JNIEnv *, jclass);

#ifdef __cplusplus
}
#endif
#endif
