/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class xflaim_CHECKINFO_CheckPhaseCodes */

#ifndef _Included_xflaim_CHECKINFO_CheckPhaseCodes
#define _Included_xflaim_CHECKINFO_CheckPhaseCodes
#ifdef __cplusplus
extern "C" {
#endif
#undef xflaim_CHECKINFO_CheckPhaseCodes_CHECK_GET_DICT_INFO
#define xflaim_CHECKINFO_CheckPhaseCodes_CHECK_GET_DICT_INFO 1L
#undef xflaim_CHECKINFO_CheckPhaseCodes_CHECK_B_TREE
#define xflaim_CHECKINFO_CheckPhaseCodes_CHECK_B_TREE 2L
#undef xflaim_CHECKINFO_CheckPhaseCodes_CHECK_AVAIL_BLOCKS
#define xflaim_CHECKINFO_CheckPhaseCodes_CHECK_AVAIL_BLOCKS 3L
#undef xflaim_CHECKINFO_CheckPhaseCodes_CHECK_RS_SORT
#define xflaim_CHECKINFO_CheckPhaseCodes_CHECK_RS_SORT 4L
#undef xflaim_CHECKINFO_CheckPhaseCodes_CHECK_DOM_LINKS
#define xflaim_CHECKINFO_CheckPhaseCodes_CHECK_DOM_LINKS 5L
#ifdef __cplusplus
}
#endif
#endif
