/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class xflaim_DbStats */

#ifndef _Included_xflaim_DbStats
#define _Included_xflaim_DbStats
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     xflaim_DbStats
 * Method:    initIDs
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_xflaim_DbStats_initIDs
  (JNIEnv *, jclass);

#ifdef __cplusplus
}
#endif
#endif
