/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class xflaim_SlabUsage */

#ifndef _Included_xflaim_SlabUsage
#define _Included_xflaim_SlabUsage
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     xflaim_SlabUsage
 * Method:    initIDs
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_xflaim_SlabUsage_initIDs
  (JNIEnv *, jclass);

#ifdef __cplusplus
}
#endif
#endif
