/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class xflaim_CountTimeStat */

#ifndef _Included_xflaim_CountTimeStat
#define _Included_xflaim_CountTimeStat
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     xflaim_CountTimeStat
 * Method:    initIDs
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_xflaim_CountTimeStat_initIDs
  (JNIEnv *, jclass);

#ifdef __cplusplus
}
#endif
#endif
