/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class xflaim_FlmInsertLoc */

#ifndef _Included_xflaim_FlmInsertLoc
#define _Included_xflaim_FlmInsertLoc
#ifdef __cplusplus
extern "C" {
#endif
#undef xflaim_FlmInsertLoc_FLM_FIRST_CHILD
#define xflaim_FlmInsertLoc_FLM_FIRST_CHILD 1L
#undef xflaim_FlmInsertLoc_FLM_LAST_CHILD
#define xflaim_FlmInsertLoc_FLM_LAST_CHILD 2L
#undef xflaim_FlmInsertLoc_FLM_PREV_SIB
#define xflaim_FlmInsertLoc_FLM_PREV_SIB 3L
#undef xflaim_FlmInsertLoc_FLM_NEXT_SIB
#define xflaim_FlmInsertLoc_FLM_NEXT_SIB 4L
#ifdef __cplusplus
}
#endif
#endif
