/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class xflaim_ImportStats */

#ifndef _Included_xflaim_ImportStats
#define _Included_xflaim_ImportStats
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     xflaim_ImportStats
 * Method:    initIDs
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_xflaim_ImportStats_initIDs
  (JNIEnv *, jclass);

#ifdef __cplusplus
}
#endif
#endif
