/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class xflaim_BackupClient */

#ifndef _Included_xflaim_BackupClient
#define _Included_xflaim_BackupClient
#ifdef __cplusplus
extern "C" {
#endif
#ifdef __cplusplus
}
#endif
#endif
