/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class xflaim_CacheUsage */

#ifndef _Included_xflaim_CacheUsage
#define _Included_xflaim_CacheUsage
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     xflaim_CacheUsage
 * Method:    initIDs
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_xflaim_CacheUsage_initIDs
  (JNIEnv *, jclass);

#ifdef __cplusplus
}
#endif
#endif
