/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class xflaim_FlmDomNodeType */

#ifndef _Included_xflaim_FlmDomNodeType
#define _Included_xflaim_FlmDomNodeType
#ifdef __cplusplus
extern "C" {
#endif
#undef xflaim_FlmDomNodeType_INVALID_NODE
#define xflaim_FlmDomNodeType_INVALID_NODE 0L
#undef xflaim_FlmDomNodeType_DOCUMENT_NODE
#define xflaim_FlmDomNodeType_DOCUMENT_NODE 1L
#undef xflaim_FlmDomNodeType_ELEMENT_NODE
#define xflaim_FlmDomNodeType_ELEMENT_NODE 2L
#undef xflaim_FlmDomNodeType_DATA_NODE
#define xflaim_FlmDomNodeType_DATA_NODE 3L
#undef xflaim_FlmDomNodeType_COMMENT_NODE
#define xflaim_FlmDomNodeType_COMMENT_NODE 4L
#undef xflaim_FlmDomNodeType_CDATA_SECTION_NODE
#define xflaim_FlmDomNodeType_CDATA_SECTION_NODE 5L
#undef xflaim_FlmDomNodeType_ANNOTATION_NODE
#define xflaim_FlmDomNodeType_ANNOTATION_NODE 6L
#undef xflaim_FlmDomNodeType_PROCESSING_INSTRUCTION_NODE
#define xflaim_FlmDomNodeType_PROCESSING_INSTRUCTION_NODE 7L
#undef xflaim_FlmDomNodeType_ATTRIBUTE_NODE
#define xflaim_FlmDomNodeType_ATTRIBUTE_NODE 8L
#undef xflaim_FlmDomNodeType_ANY_NODE_TYPE
#define xflaim_FlmDomNodeType_ANY_NODE_TYPE 65535L
#ifdef __cplusplus
}
#endif
#endif
