/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class xflaim_InsertLoc */

#ifndef _Included_xflaim_InsertLoc
#define _Included_xflaim_InsertLoc
#ifdef __cplusplus
extern "C" {
#endif
#undef xflaim_InsertLoc_XFLM_ROOT
#define xflaim_InsertLoc_XFLM_ROOT 0L
#undef xflaim_InsertLoc_XFLM_FIRST_CHILD
#define xflaim_InsertLoc_XFLM_FIRST_CHILD 1L
#undef xflaim_InsertLoc_XFLM_LAST_CHILD
#define xflaim_InsertLoc_XFLM_LAST_CHILD 2L
#undef xflaim_InsertLoc_XFLM_PREV_SIB
#define xflaim_InsertLoc_XFLM_PREV_SIB 3L
#undef xflaim_InsertLoc_XFLM_NEXT_SIB
#define xflaim_InsertLoc_XFLM_NEXT_SIB 4L
#undef xflaim_InsertLoc_XFLM_ATTRIBUTE
#define xflaim_InsertLoc_XFLM_ATTRIBUTE 5L
#ifdef __cplusplus
}
#endif
#endif
