/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class xflaim_LFileStats */

#ifndef _Included_xflaim_LFileStats
#define _Included_xflaim_LFileStats
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     xflaim_LFileStats
 * Method:    initIDs
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_xflaim_LFileStats_initIDs
  (JNIEnv *, jclass);

#ifdef __cplusplus
}
#endif
#endif
