/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class xflaim_DbCopyStatus */

#ifndef _Included_xflaim_DbCopyStatus
#define _Included_xflaim_DbCopyStatus
#ifdef __cplusplus
extern "C" {
#endif
#ifdef __cplusplus
}
#endif
#endif
