/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class xflaim_OStream */

#ifndef _Included_xflaim_OStream
#define _Included_xflaim_OStream
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     xflaim_OStream
 * Method:    _release
 * Signature: (J)V
 */
JNIEXPORT void JNICALL Java_xflaim_OStream__1release
  (JNIEnv *, jobject, jlong);

#ifdef __cplusplus
}
#endif
#endif
