/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class xflaim_IndexStatus */

#ifndef _Included_xflaim_IndexStatus
#define _Included_xflaim_IndexStatus
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     xflaim_IndexStatus
 * Method:    initIDs
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_xflaim_IndexStatus_initIDs
  (JNIEnv *, jclass);

#ifdef __cplusplus
}
#endif
#endif
