/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class xflaim_DbRenameStatus */

#ifndef _Included_xflaim_DbRenameStatus
#define _Included_xflaim_DbRenameStatus
#ifdef __cplusplus
extern "C" {
#endif
#ifdef __cplusplus
}
#endif
#endif
