/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class xflaim_Stats */

#ifndef _Included_xflaim_Stats
#define _Included_xflaim_Stats
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     xflaim_Stats
 * Method:    initIDs
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_xflaim_Stats_initIDs
  (JNIEnv *, jclass);

#ifdef __cplusplus
}
#endif
#endif
