/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class xflaim_DictType */

#ifndef _Included_xflaim_DictType
#define _Included_xflaim_DictType
#ifdef __cplusplus
extern "C" {
#endif
#undef xflaim_DictType_ELEMENT_DEF
#define xflaim_DictType_ELEMENT_DEF 1L
#undef xflaim_DictType_ATTRIBUTE_DEF
#define xflaim_DictType_ATTRIBUTE_DEF 2L
#undef xflaim_DictType_PREFIX_DEF
#define xflaim_DictType_PREFIX_DEF 3L
#undef xflaim_DictType_ENCRYPTION_DEF
#define xflaim_DictType_ENCRYPTION_DEF 4L
#undef xflaim_DictType_COLLECTION_DEF
#define xflaim_DictType_COLLECTION_DEF 5L
#undef xflaim_DictType_INDEX_DEF
#define xflaim_DictType_INDEX_DEF 6L
#ifdef __cplusplus
}
#endif
#endif
