/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class xflaim_LockStats */

#ifndef _Included_xflaim_LockStats
#define _Included_xflaim_LockStats
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     xflaim_LockStats
 * Method:    initIDs
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_xflaim_LockStats_initIDs
  (JNIEnv *, jclass);

#ifdef __cplusplus
}
#endif
#endif
