/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class xflaim_LockType */

#ifndef _Included_xflaim_LockType
#define _Included_xflaim_LockType
#ifdef __cplusplus
extern "C" {
#endif
#undef xflaim_LockType_FLM_LOCK_NONE
#define xflaim_LockType_FLM_LOCK_NONE 0L
#undef xflaim_LockType_FLM_LOCK_EXCLUSIVE
#define xflaim_LockType_FLM_LOCK_EXCLUSIVE 1L
#undef xflaim_LockType_FLM_LOCK_SHARED
#define xflaim_LockType_FLM_LOCK_SHARED 2L
#ifdef __cplusplus
}
#endif
#endif
