/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class xflaim_CREATEOPTS */

#ifndef _Included_xflaim_CREATEOPTS
#define _Included_xflaim_CREATEOPTS
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     xflaim_CREATEOPTS
 * Method:    initIDs
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_xflaim_CREATEOPTS_initIDs
  (JNIEnv *, jclass);

#ifdef __cplusplus
}
#endif
#endif
